apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-deployment
  namespace: sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: 654654563130.dkr.ecr.us-east-1.amazonaws.com/sample-repo:sample-app
        ports:
        - containerPort: 80
